apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # These values are base64 encoded. 
  # For example, to get the base64 value for 'user', run: echo -n 'user' | base64
  DB_USER: dXNlcg== # user
  DB_PASSWORD: cGFzc3dvcmQ= # password
  DB_NAME: bXlkYXRhYmFzZQ== # mydatabase
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg== # minioadmin
  MINIO_SECRET_KEY: bWluaW9hZG1pbg== # minioadmin
  # Example for a root password, if needed by a service
  # MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # rootpassword
