apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer
  ports:
  - port: 80 # The port the service is exposed on
    targetPort: 8080 # The port the container is running on
    protocol: TCP
  selector:
    app: go-app # Selects the pods to send traffic to
